### ISSUE TITLE
Problem with the installation

### ISSUE THREAD

**Issue by beherit** [roryrjb/ngx-system-info#1]
Is this module still working? I have problem with installing it on nginx 1.10.3 and newer. Could You add support for dynamic loading? Maybe with such feature the installation will be simpler.

**Comment by roryrjb** [comment]
@beherit I haven't used it in a while but it _was_ working on `v1.12.x`, I hadn't actually checked `v1.10.x` but I will and let you know/fix it :+1: will also look into dynamic loading.

**Comment by roryrjb** [comment]
@beherit I have now tested this module against the following versions:

* 1.6.3
* 1.8.1
* 1.10.3
* 1.12.2
* 1.14.0

..and everything compiles and works fine. This can be verified with the now included `Dockerfile`. I am going to close this issue and open another one which addresses the support for dynamic loading, which I'll look into.
